### ISSUE TITLE
I2C sensors list

### ISSUE THREAD

**Issue by vvs551** [bitbank2/I2C_Detector#1]
Could you continue the list of sensors in your project?
Or may be you can give an idea how to do it by myself)
There are sensors which I need to detect::
HTU21
BH1750
TCS34725
GYUS42
DHT12
MLX90614
ADS1100
MCP9600
MAX30100
VEML6070
QMC5883

**Comment by bitbank2** [comment]
Thanks for the suggestion. I don't have access to any of those sensors (without waiting weeks to receive them from China). It's pretty straightforward if they have a "WHO_AM_I" register in them like most STMicro sensors do. If not, there may be some default values that can be read to do the same thing. Take a look at the existing code and it should be fairly obvious how to add more sensors to the supported list. I welcome your additions and you can request to add them with a git merge request.
