### ISSUE TITLE
Wire.requestFrom() should not be used with Wire.beginTransmission().

### ISSUE THREAD

**Issue by Koepel** [bitbank2/I2C_Detector#2]
In the file "I2C_Detector/I2C_Detector.ino" there is a `Wire.beginTransmission()` before a `Wire.requestFrom()`. That `Wire.beginTransmission()` at line 80 may be removed.

Regardless which Wire (or Wire compatible) library you use, it does not belong there.

Explanation: [Common-mistakes#3](https://github.com/Koepel/How-to-use-the-Arduino-Wire-library/wiki/Common-mistakes#3)

P.S.: I have added the BitBang_I2C to [the list](https://github.com/Testato/SoftwareWire/wiki/Arduino-I2C-libraries).

**Comment by bitbank2** [comment]
Thanks for the tip - fixed.
